title: Essays
description: Yaps, blabs, and scribbles authored by the people of Hack Club
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  essays:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"
      author: "Hack Club"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Feed settings
feed:
  collections:
    - essays

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 